### ISSUE TITLE
v.4 Server setup problem

### ISSUE THREAD

**Issue by rlefever** [sqall01/alertR#14]
Fresh install on Raspian Jessie, fully updated.

pi@raspberrypi:~ $ python ~/alertR/alertRinstaller.py -i server -t server/
06/08/2016 11:29:15 INFO: [alertRinstaller.py]: Checking the dependencies.
06/08/2016 11:29:15 INFO: [alertRinstaller.py]: Checking module 'MySQLdb'.
06/08/2016 11:29:15 INFO: [alertRinstaller.py]: Files to modify: 1; New files: 0
06/08/2016 11:29:15 INFO: [alertRinstaller.py]: Downloading file: 'config/config.xml.template'
06/08/2016 11:29:16 INFO: [alertRinstaller.py]: Download: 10%
06/08/2016 11:29:16 INFO: [alertRinstaller.py]: Download: 20%
06/08/2016 11:29:16 INFO: [alertRinstaller.py]: Download: 40%
06/08/2016 11:29:16 INFO: [alertRinstaller.py]: Download: 50%
06/08/2016 11:29:16 INFO: [alertRinstaller.py]: Download: 70%
06/08/2016 11:29:16 INFO: [alertRinstaller.py]: Download: 80%
06/08/2016 11:29:16 INFO: [alertRinstaller.py]: Download: 100%
06/08/2016 11:29:16 ERROR: [alertRinstaller.py]: Temporary file does not have the correct hash.
06/08/2016 11:29:16 ERROR: [alertRinstaller.py]: Downloading files from the repository failed. Aborting update process.
06/08/2016 11:29:16 ERROR: [alertRinstaller.py]: Installation failed.

Thanks for all your help.

**Comment by sqall01** [comment]
Ah sorry, forgot to update the file hash. Just did it. Should be working
in a few minutes.

On 08.06.2016 13:49, rlefever wrote:
> Fresh install on Raspian Jessie, fully updated.
> 
> pi@raspberrypi:~ $ python ~/alertR/alertRinstaller.py -i server -t server/
> 06/08/2016 11:29:15 INFO: [alertRinstaller.py]: Checking the dependencies.
> 06/08/2016 11:29:15 INFO: [alertRinstaller.py]: Checking module 'MySQLdb'.
> 06/08/2016 11:29:15 INFO: [alertRinstaller.py]: Files to modify: 1; New files: 0
> 06/08/2016 11:29:15 INFO: [alertRinstaller.py]: Downloading file: 'config/config.xml.template'
> 06/08/2016 11:29:16 INFO: [alertRinstaller.py]: Download: 10%
> 06/08/2016 11:29:16 INFO: [alertRinstaller.py]: Download: 20%
> 06/08/2016 11:29:16 INFO: [alertRinstaller.py]: Download: 40%
> 06/08/2016 11:29:16 INFO: [alertRinstaller.py]: Download: 50%
> 06/08/2016 11:29:16 INFO: [alertRinstaller.py]: Download: 70%
> 06/08/2016 11:29:16 INFO: [alertRinstaller.py]: Download: 80%
> 06/08/2016 11:29:16 INFO: [alertRinstaller.py]: Download: 100%
> 06/08/2016 11:29:16 ERROR: [alertRinstaller.py]: Temporary file does not have the correct hash.
> 06/08/2016 11:29:16 ERROR: [alertRinstaller.py]: Downloading files from the repository failed. Aborting update process.
> 06/08/2016 11:29:16 ERROR: [alertRinstaller.py]: Installation failed.
> 
> Thanks for all your help.
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sqall01/alertR/issues/14
> 

-- 

Andre Pawlowski

-------------------------------------------------------------------

If your life's no more important than anyone else's,
sign your donor card and kill yourself.
	-House M.D. (Dr. Gregory House)

**Comment by rlefever** [comment]
Worked. Thanks.
