### ISSUE TITLE
Keypad Autologin

### ISSUE THREAD

**Issue by rlefever** [sqall01/alertR#17]
I have setup the keypad on a pi zero. All goes fine until the last few lines where the passwd file and inittab file are edited. What changes need to be made for this to work with Jessie which no longer uses inittab but uses systemd? I successfully got the keypad user to autologin but when I change the passwd file it fails and keeps trying to autologin over and over.

Thank you for your time and work on this project. I enjoy it alot.

**Update:** Not exactly sure how but I go the  login to show errors instead of re-logging in. I corrected a couple of errors in the config including the fact that the server host value needed to be an IP. Seems the system could not resolve the server's hostname.

Now the alertR keypad manager displays on boot but when I key the pass code it prompts for a password. Figured out that it is the normal login behind the display. if I put in pi and raspberry I can login with the following errors:

-bash: cannot set terminal process group (505): Inappropriate ioctl for device
-bash: no job control on this shell

Any assistance greatly appreciated.

**Comment by sqall01** [comment]
Thanks for your words :)

I will try to recreate the issue under Jessie. At the moment I have no idea how to tackle it. Perhaps I get an idea :)

**Comment by rlefever** [comment]
Never mind. I started from scratch with a clean image and all worked out.
