### ISSUE TITLE
Webcam integration

### ISSUE THREAD

**Issue by lshaheen** [sqall01/alertR#20]
This is not so much an an issue as it is a question. How does alertR integrate with a webcam? I saw it was mentioned in the tutorials that a sensor could be used to trigger a webcam to play on XBMC. Would it be possible to use a webcam attached to one of the Pis? Could you view the video through the web access client at will, or only if an alert was triggered?

Thanks, looks like an awesome project!

**Comment by sqall01** [comment]
Hi,

sorry there is no direct webcam integration. You could achieve this by using the alert executer client and execute a script that shows the image of the webcam on XBMC when a sensor alert is triggered (this is what I do when someone uses my door bell while I am not home to send me a picture via email). On the web access you can not view the webcam image.

Cheers,

sqall

**Comment by lshaheen** [comment]
Ok, thanks.
