### ISSUE TITLE
Wrong file name in Example Configuration for Web Mobile Manager

### ISSUE THREAD

**Issue by cerikss8** [sqall01/alertR#21]
Hi!
Just to help out-
I have found a fault in the code in your example configuration for Web Mobile Manager in the section for web page.
You have written :
#################### configure web page ####################

sqall@webserver:/var/www/alertR/config$ vim config.conf
----------

But it has to be .php to be able to work with the index file as It calls for the script with */config/config.php*
It´s not a problem when you just delete the .templet on the example config but if you read the Example Config as I did then It can cause problem when starting the web page.

-- now my page is up and running :-) 
Keep up the good work!
Cheers
/CE

**Comment by sqall01** [comment]
Thanks. I fixed it.
