### ISSUE TITLE
Issue with Keypad auto login *SOLVED*

### ISSUE THREAD

**Issue by cerikss8** [sqall01/alertR#22]
Hi!
I have a problem with starting the shellwrapper for the Keypad.
Since Jessie do not use Inittab any more and use Systemd instead the tutorial is slightly missleading.
I have made Systemd to auto start "Keypad" user but I can't really get my hands on how to make the shellwrapper to start with the user "Keypad" hence the python program needs to be with root permission.
For the moment I start the keypad manually.
What to do?!

/CE

**Comment by sqall01** [comment]
The documentation you used is outdated (as the document says) and can therefore be misleading. I have no idea what changed in Jessie that it will not work. When I update to Jessie or reinstall a Pi, I will take a look at it. If you find a solution before I find one, it would be nice if you can post it here or add it to the wiki.

Cheers,
sqall

**Comment by cerikss8** [comment]
Thank you for the answer! I'll post a solution when I have figured it out (if I do) :-)

**Comment by cerikss8** [comment]
Hi! 
I'm still trying to find a way to get the login script to start at login but I have Errno 13 "permission denied" problem. I'm trying to start the script from .bashrc instead inittab due to systemd.
Is there some one that have a working kiosk mode running for the keypad!?

CE

**Comment by sqall01** [comment]
In the beginning of next year I will move to a new apartment. Then I will reinstall all my Raspberry Pis and therefore reinstall my alertR setup. When I am doing this, I have also to figure out how to use the kiosk mode again. Perhaps I find a solution. I will keep you updated.

**Comment by cerikss8** [comment]
Hi!
After some considerable time struggeling with auto login on keypad with systemd I´v solved it.
I made a .conf unit file in systemd getty directory with:
nano  /etc/systemd/system/getty@tty1.service.d/override.conf
And write in .conf:
[Service]
ExecStart=
ExecStart=-/usr/bin/sudo -H /home/keypad/managerClientKeypad/alertRclient.py
StandardInput=tty
StandardOutput=tty

To be able to execute alertRclient.py use "/use/bin/sudo -H" in the ExecStart line.
Reload the unit file and restart the service with:
systemctl daemon-reload; systemctl restart getty@tty1.service

All is explained in this tutorial- https://raymii.org/s/tutorials/Run_software_on_tty1_console_instead_of_login_getty.html

/cheers
CE

**Comment by sqall01** [comment]
Nice. Thank you very much. As soon as I reinstall my system I will add this to a new tutorial :)

**Comment by sqall01** [comment]
Just to let you know. I just uploaded a tutorial for the keypad manager. Thanks to you I did not have to search to solve the autologin with systemd. The tutorial can be found [here](https://github.com/sqall01/alertR/wiki/Tutorial-ManagerClientKeypad).

Thanks
sqall
