### ISSUE TITLE
alertRinstaller.py SyntaxError

### ISSUE THREAD

**Issue by FoxKyong** [sqall01/alertR#23]
Hi,
I just wanted to install alerR but alertRinstaller.py is not working. If I run it I get:

```
pi@fox-pi:~ $ python alertRinstaller.py -l
  File "alertRinstaller.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

I tried it on Raspberry Pi with Python 2.7.9 and Arch linux with Python 3.6.1.

**Comment by FoxKyong** [comment]
I am sorry, I just noticed that wget didn't download it correctly. It is working now.

**Comment by sqall01** [comment]
Issues that resolves themselves I like the most :) Have fun using alertR :)
