### ISSUE TITLE
Feature Request?: Scheduled alarm activation 

### ISSUE THREAD

**Issue by qpaz** [sqall01/alertR#26]
is it possible to schedule the alarm activation in v0.5?

**Comment by sqall01** [comment]
No, this feature is not build in. But it is a great idea :)

However, if you want to have this feature right now, you can set up the managerClientDatabase, activate its local unix socket and write a script which sends an activate/deactivate signal to it on the time you want. The protocol is described here:

https://github.com/sqall01/alertR/wiki/Protocol#protocol_schematics_manager_database_option

and PHP code that does this can be seen here

https://github.com/sqall01/alertR/blob/master/webMobileManager/server/index.php#L31

This would be a quick solution to this.

**Comment by qpaz** [comment]
awesome. thanks for such a nice alert system tool and the great support behind it. I really appreciate that. I did it in a 5 minutes dirty way...called it with php on cmd line in crontab with argv 0 or 1....
<?php
// written by sqall
// twitter: https://twitter.com/sqall01
// blog: http://blog.h4des.org
// github: https://github.com/sqall01
// 
// Licensed under the GNU Public License, version 2.
require_once("/var/www/alertr/config/config.php");
if($configUnixSocketActive) {
	// validate integer
	$activate = intval($argv[1]);
	// open connection to local manager client
	@$fd = stream_socket_client(
		"unix://" . $configUnixSocketPath, $errno, $errstr, 5);
	// check if connection could be established
	if ($errno != 0) {
		echo "Error: Could not connect to local manager client<br />";
		echo "Reason: " . $errstr . "\n";
		exit(1);
	}
	// send activate/deactivate according to the given parameter
	$message = array();
	$message["message"] = "option";
	if($activate === 0) {
		$payload = array();
		$payload["optionType"] = "alertSystemActive";
		$payload["value"] = 0;
		$payload["timeDelay"] = 0;
		$message["payload"] = $payload;
	}
	else {
		$payload = array();
		$payload["optionType"] = "alertSystemActive";
		$payload["value"] = 1;
		$payload["timeDelay"] = 0;
		$message["payload"] = $payload;	
	}
	fwrite($fd, json_encode($message));
	// get response
	$response = json_decode(fread($fd, 1024), true);
	if($response == NULL) {
		echo "Error: Could not decode server response.";
		exit(1);
	}
	else {
		if($response["payload"]["result"] != "ok") {
			echo "Error: Received response is not 'ok': "
				. $response["payload"]["result"];
			exit(1);
		}
	}
	// close connection
	fclose($fd);
	// wait two seconds in order to let the server process the request
	sleep(2);
}
?>
