### ISSUE TITLE
Server error after update to server 0.503

### ISSUE THREAD

**Issue by cerikss8** [sqall01/alertR#27]
Hi!
First I updated the alertClientMail and managerClientConsol to 0.501 with server version 0.500 and it was running well. Then I updated the server side to 0.503 and I ended up with this error in the log:
 
10/21/2017 11:56:42 ERROR: [alertRserver.py]: Could not parse config.
Traceback (most recent call last):
  File "./alertRserver.py", line 1320, in <module>
    sensor.description = str(item.attrib["description"])
KeyError: 'description'

Unfortunatelly I did not backup my working config on the server..... but anyway that is on me.
When I check status on server thru systemctl I get:

● alertRserver.service - alertR Server
   Loaded: loaded (/etc/systemd/system/alertRserver.service; enabled)
   Active: active (exited) since lör 2017-10-21 11:40:49 CEST; 33min ago
  Process: 2405 ExecStop=/etc/init.d/alertRserver.sh stop (code=exited, status=1/FAILURE)
  Process: 2413 ExecStart=/etc/init.d/alertRserver.sh start (code=exited, status=0/SUCCESS)
 Main PID: 2413 (code=exited, status=0/SUCCESS)

okt 21 11:40:49 lill-clas systemd[1]: Started alertR Server.
okt 21 11:40:49 lill-clas alertRserver.sh[2413]: Starting daemon: alertRserver:.
okt 21 11:48:17 lill-clas systemd[1]: Started alertR Server.
okt 21 11:49:31 lill-clas systemd[1]: Started alertR Server.
okt 21 11:50:07 lill-clas systemd[1]: Started alertR Server.
okt 21 11:54:55 lill-clas systemd[1]: Started alertR Server.
okt 21 11:55:30 lill-clas systemd[1]: Started alertR Server.

Is there any way to reverse the update back to 0.500 or is it something I am missing on restarting the system.

//CE

**Comment by sqall01** [comment]
Did you modify the configuration file after the update? The configuration file has changed from 0.501 to 0.503. But just minor changes. The error with parsing the config file looks like it. The internal sensors now have a description field.

**Comment by cerikss8** [comment]
Hi!
My mistake! It's running now! I did miss out in some part of the config file. From the beginning I didn't see what the changes was.

//CE

**Comment by sqall01** [comment]
Yeah, this is a good point. Somehow I have to think about highlighting changes from the previous config better. But at the moment I do not now how ...
