### ISSUE TITLE
Problem in config managerClientDatabase NameError: name 'updateServer' is not defined

### ISSUE THREAD

**Issue by qpaz** [sqall01/alertR#30]
Hi sqall01,

just updated this great piece of software... got anything to work, except managerClientDatabase.
I updated server to 0.504 and managerClientDatabase to 0.501, both from 0.500.... I used the update script, checked the configs twice, but got no clue on this one... maybe you can help.... thx

Manager Start:
python alertRclient.py 
Traceback (most recent call last):
  File "alertRclient.py", line 312, in <module>
    globalData.versionInformer = VersionInformer(updateServer, updatePort,
NameError: name 'updateServer' is not defined

Server Log:
12/28/2018 12:33:30 INFO: [server.pyc]: Client connected (X.X.X.X:41274).
12/28/2018 12:33:32 INFO: [storage.pyc]: Node with username 'ZZZZZ' already exists in database.
12/28/2018 12:33:32 INFO: [storage.pyc]: Manager already exists in database.
12/28/2018 12:33:32 INFO: [server.pyc]: Communication initialized (X.X.X.X:41274).
12/28/2018 12:33:32 INFO: [server.pyc]: Client disconnected (X.X.X.X:41274).
12/28/2018 12:33:32 ERROR: [server.pyc]: Receiving CTS failed (X.X.X.X:41274).
Traceback (most recent call last):
  File "/opt/alertr/server/lib/server.py", line 923, in _initiateTransaction
    data = self.sslSocket.recv(BUFSIZE)
  File "/usr/lib/python2.7/socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
12/28/2018 12:33:32 ERROR: [server.pyc]: Sending state change to manager failed (X.X.X.X:41274).

**Comment by sqall01** [comment]
Oh, it seems the version gathering process is started even if the update mechanism is deactivated. It should be fixed now. Can you please update the managerClientDatabase again (to 0.501-2) and tell me if everything works now?

**Comment by qpaz** [comment]
now it works, good job. thanks, appreciate that
