### ISSUE TITLE
Playing (no)sound from keypad to bluetooth speaker

### ISSUE THREAD

**Issue by cerikss8** [sqall01/alertR#32]
Hi!
I'm trying to make the audio.py to play the .wav files to a bluetooth speaker! instead of the inbuilt 3.5 jack.
I have tryed different setup in the file but no sound is coming out off the speaker.
The terminal input looks like this - 
aplay -D bluealsa:HCI=hci0,DEV=00:58:76:45:A3:A2,PROFILE=a2dp /home/alertr/managerClientKeypad/sounds/warning.wav - 
and that gets me a sound output!
But in the audio.py file I have tryed this - 
(["aplay", "-D bluealsa:HCI=hci0 DEV=00:58:76:45:A3:A2 PROFILE=a2dp", "fileLocation"], stdout=subprocess.PIPE, stderr=subprocess.PIPE) - 
Returns no error and the keypad terminal turn to activated/ deactivated but no sound from the speaker.
With bluetooth it will be much cleaner setup beside the terminal thats why I'm trying to get this to work. I have tryed other setups according to aplay -help page, only return more errors.
Some idea of whats going wrong here!?

//Clas

**Comment by sqall01** [comment]
Hi,

can you give me the exact line you have changed? Because if it is the one you wrote:

`(["aplay", "-D bluealsa:HCI=hci0 DEV=00:58:76:45:A3:A2 PROFILE=a2dp", "fileLocation"]`

It has an error and we can probably fix it real quick.

Cheers,
sqall

**Comment by cerikss8** [comment]
Hi!
The line is in the lib/audio.py and it is as I wrote it, I added this to
subprocess.Popen "-D bluealsa:HCI=hci0 DEV=00:58:76:45:A3:A2 PROFILE=a2dp".
But I discovered I hade permission problem with the user "alertr" I could
not even play the warning file in the terminal under that user. So I have
now put the keypad manager instance under "pi" so that I can play all file
as pi or root. I have also created a .asoundrc file to shorten the command
to   p = subprocess.Popen(["aplay", "-D", "bluealsa", fileLocation],
stdout=subprocess.PIPE,stderr=subprocess.PIPE) but still no output to
bluetooth speaker!? strange! or..I'm just stupid

//Clas

Den tis 4 juni 2019 kl 12:49 skrev Andre Pawlowski <notifications@github.com

**Comment by sqall01** [comment]
So, I actually do not know in which group the `alertr` user has to be in order for it to play the sound via bluetooth. From your post I did not understand if you know can play a sound manually on the terminal with aplay via the bluetooth speakers as user `alertr`. This is definitely the first thing to check (and fix if it does not work).

Next is still the code part. Why I am asking again is the following: every part of the command line has to be a single element. So, after googling aplay and bluealsa it should look something like this:

`
p = subprocess.Popen(["aplay", "-D", "bluealsa:HCI=hci0,DEV=00:58:76:45:A3:A2,PROFILE=a2dp", fileLocation], stdout=subprocess.PIPE,stderr=subprocess.PIPE)
`

However, I understand that the `.asoundrc` file now contains settings so you just have to write "aplay -D bluealsa file.wav" on the terminal. Here the next question: did you create the .asoundrc file for the correct user (namely `alertr` in this case)? Can the `alertr` user execute the command in the terminal and play the sound?

Cheers,
sqall

**Comment by cerikss8** [comment]
Hi!
Under AlertR user I could not play any sound manually thru terminal even, only error ” permission denyed to play file” so I installed the keypad under ~/pi but still no sound output. I’m do now have a /.asoundrc in pi home folder so that I can play sound thru terminal with ’aplay -D bluealas file.wav’. 
Should It be in the audio.py-  [”aplay”, ”-D”, ”bluealsa”, fileLocation], - I will check how I have set it now and come back to you 


Cheers
Clas
Skickat från min iPhone

**Comment by cerikss8** [comment]
Hi!
It’s solved!
I run it under pi user and with the code as you have wrote it. Maby I forgot to reload the getty@tty.d after I had made changes and thats why it did not redirected the sound output to bluetooth speaker. 

Thank you for all your input

Cheers
Clas

Skickat från min iPhone

**Comment by sqall01** [comment]
Glad to hear it :)

Cheers
sqall
