### ISSUE TITLE
Error in dependency version check of installer

### ISSUE THREAD

**Issue by fgschaefer** [sqall01/alertR#35]
In [the installer](https://github.com/sqall01/alertR/blob/master/alertRinstaller.py#L880) the check for correct dependency version is
```
if int(installedVersion[i]) > int(neededVersion[i]):
    versionCorrect = True
    break
```
But `versionCorrect` is set to `False` initially, this fails if the already installed version matches exactly the needed version.
Should `versionCorrect` be set to `True` initially?

**Comment by sqall01** [comment]
You are completely right. The initial value should be `True`. Though I am curious why I did not run into this bug before. I fixed this bug in the installer (as well as in the update scripts). Thanks :)
