### ISSUE TITLE
Missing files after server installation

### ISSUE THREAD

**Issue by fgschaefer** [sqall01/alertR#36]
After installing the server today via the installer, i'm getting `ModuleNotFoundError: No module named 'lib.config'` when trying to run it.

I don't know about the function of this json file, but I noticed a change in `server/instanceInfo.json` on the [last commit](https://github.com/sqall01/alertR/commit/bd613e36708b67dddc81e79c9cdc7da46f908e5d), where all entries for `lib/config` have been removed. I guess this wasn't done intentionally?

**Comment by sqall01** [comment]
Ah you are correct. Good catch regarding the `server/instanceInfo.json` file. This file contains information for the installer/updater which files belong to an installation. I have the problem that I changed a lot in the `dev` branch which also includes local building scripts. The `server/instanceInfo.json` is created by such a script. When you reported the bug a week ago, I had the problem that I had to get a working version for the current `master` branch up and running so I could commit it. It seems I forgot the `lib/config` files while I was doing this.

Thanks, I fixed it :)
