### ISSUE TITLE
Feature Request: Activation Confirmation for not-ready sensors

### ISSUE THREAD

**Issue by akkord64** [sqall01/alertR#4]
It would be nice to have a confirmation displayed to the user acknowledging sensors (in group XX) that are in the not ready state. This notification should be displayed on the Keypad, console, and Mobile manager. This could/should be configurable per the admin and should serve as a reminder to close the windows/doors/sensors prior to activation.

**Comment by sqall01** [comment]
The Keypad manager in the current dev version has this feature now. It will have this feature in the release version 0.400 (next version). You can configure the states the sensors should not have when activating the alarm system and the manager asks for confirmation before sending the activating message to the server.

**Comment by sqall01** [comment]
Closing these issue because of no responses.
