### ISSUE TITLE
Feature request: installation and configuration assistants

### ISSUE THREAD

**Issue by tbertels** [sqall01/alertR#43]
Both the initial and following installation and configuration of AlertR could be made easier (and so the learning curve of AlertR) by creating installation and configuration scripts and assistants.

An install.sh script would install the dependencies, beginning by [the ones needed for the server](https://github.com/sqall01/alertR/wiki/Tutorial-Server#tutorial_installation).
It would also install a web server, so that the following installation could be made through a web interface on a desktop browser/smartphone browser/the AlertR app.
The web interface would then allow installing Clients as needed by executing scripts. It would also allow configuring both the server and the clients

**Comment by sqall01** [comment]
For the installation script I defensively see the benefits of this. However, this will be a bigger task than it first seems (which is the reason I did not write one yet). You have to account for the Linux distri used, also you have to make it configurable to support different usernames, locations where to install it, and other user specific settings. For the server, for example, if someone wants to only use a self-signed server certificate, or also client certificates. In my own setup, I use ansible to automate the installation of clients which is the reason I do not have an incentive at the moment to work on it in the near future.

The part with the web server I do not understand. If it is about having to configure each client separately, I have on my long-term TODO-list for AlertR a centralized configuration mechanism in mind (the server will push the configuration to the clients). But this is also more involved then it first seems (supporting different versions of the client, how react on updates on the client which also involve the configuration file, and so on).

**Comment by sqall01** [comment]
Closing these issue because of no responses.
