### ISSUE TITLE
Temperature sensor don't go back to normal state after triggered

### ISSUE THREAD

**Issue by cerikss8** [sqall01/alertR#52]
Hi!
I've discovered a problem with the ds18b20 type sensor script.
I use two sensors in the script and both are set to triggerAlert=True and triggerAlertNormal=False with threshold @ 5deg set to "LT", so both have the same setup and they do measure the temperature down to the threshold but after that one of them do not change back to normal after triggered.
Only way to get it out of triggered state is to restart the sensor service
I'm using config 0.901

Not a big problem but still...!

/CE

**Comment by sqall01** [comment]
I am currently not able to reproduce this issue. Can you answer me the following questions so I can make sure I understand it correctly and narrow the problem down?

1. Do both sensors use the same hardware temperature sensor? In other words, have both sensors in their config.xml the same sensor name (e.g., `sensorName="10-0008020b7c5d"`)?
2. Does this problem only occur for the same sensor? Or is it sometimes the first, sometimes the second sensor?
3. Does the sensor that does not change back still change its temperature data or does it hang completely?
4. Did you take a look in the logfile of the sensor client and see something that could hint why this problem occurs?

Cheers,
sqall

**Comment by cerikss8** [comment]
1. No, the sensor's has different sensorName, 28-0000074f763d  and
28-011572997dff and it's the first one that has the problem. The second one
do trigger but it goes back to normal as expected.
2. It's always sensor 28-0000074f763d.
3. The sensor stopped reading temperature values after it got stuck.
4.Sensor log:
01/08/2022 07:49:00 INFO: [ds18b20.py] Placeholder 4.937000 °C of sensor
'Temperatur i Pumphus' is below threshold (triggered).
01/08/2022 07:49:00 INFO: [core.py]: Sensor alert triggered by 'Temperatur
i Pumphus' with state 1.
01/16/2022 10:27:48 WARNING: [watchdog.py]: Stopped waiting for ping
response after 10 seconds.
01/16/2022 10:27:56 ERROR: [serverCommunication.py]: Receiving CTS failed.
Traceback (most recent call last):
  File "/home/alertr/sensorClientRaspberryPi/lib/client/core.py", line 98,
in recv
    data = self._socket.recv(buffsize)
  File "/usr/lib/python3.7/ssl.py", line 1037, in recv
    return self.read(buflen)
  File "/usr/lib/python3.7/ssl.py", line 913, in read
    return self._sslobj.read(len)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alertr/sensorClientRaspberryPi/lib/client/communication.py",
line 208, in _initiate_transaction
    data = self._connection.recv(BUFSIZE).decode("ascii")
  File "/home/alertr/sensorClientRaspberryPi/lib/client/core.py", line 101,
in recv
    raise RecvTimeout
lib.client.core.RecvTimeout
01/16/2022 10:28:03 WARNING: [watchdog.py]: Stopped waiting for ping
response after 10 seconds.
01/16/2022 10:28:08 ERROR: [watchdog.py]: Connection to server has died.
01/16/2022 10:28:08 INFO: [serverCommunication.py] Reconnecting to server.
01/16/2022 10:28:08 ERROR: [serverCommunication.py]: Error received:
'username already in use'.
01/16/2022 10:28:08 ERROR: [serverCommunication.py]: Version verification
and authentication failed.
01/16/2022 10:28:08 ERROR: [watchdog.py]: Reconnecting failed. Retrying in
5 seconds.

It seems like that the sensor can't report back to server after it has gone
back to normal state due to 'username already in use'
After a restart of the service everything works again until it triggers

I also run a instance of the sensors on a backup server with version 0.800
on the sensors and server and that one don't have this problem,


/Clas

Den lör 22 jan. 2022 kl 10:02 skrev Andre Pawlowski <
***@***.***>:

**Comment by sqall01** [comment]
I think I fixed it. Can you please update your RaspberryPi Sensor client to version 0.901-2? And could you provide me feedback if everything works or if it still crashes?

**Comment by cerikss8** [comment]
Hi!
You fixed it!
The sensor can now go from triggered back to normal
/CE

Skickat från min iPhone
