### ISSUE TITLE
Error 404: installing server on windows

### ISSUE THREAD

**Issue by jmlesfrite** [sqall01/alertR#54]
When running .\alertRinstaller.py -i server -t ./server/

I hit this exception:

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/sqall01/alertR/master/server/shared_code/all/lib/globalData/baseObjects.py

**Comment by sqall01** [comment]
The software does not wors on Windows. My guess is that it does not work here because it cannot process the symbolic links correctly on Windows. Sorry.
