### ISSUE TITLE
Feature Request : MQTT Manager

### ISSUE THREAD

**Issue by akkord64** [sqall01/alertR#6]
Enable an MQTT manager who can subscribe to alert levels send standardized MQTT messages to an MQTT broker. This will allow for expanded integration of AlertR other management platforms.

**Comment by nibelungen** [comment]
Hey, 
mqtt is a great idea and a way to save a lot of sms or e-mail traffic :)
With node-red it is then easily possible to trigger other events and expand the functions with ease.
MQTT also supports encryption - to communicate over MQTT imho its very important, without it anyone can publish messages to a broker... that wouldnt be good for this system....

At the moment i set up a new environment with two rPI and some reed-switches, i will also set up mosquitto server and node red - if you need some dev testing, let me know!

best regards & a happy new year

**Comment by sqall01** [comment]
Closing these issue because of no responses.
